spring.application.name=pokemon-service
pokemon.team.max-count=6
pokemon.pc-box.max-count=30
skaro.pokeapi.base-uri=https://pokeapi.co/api/v2/
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=